FROM debian:stable-slim

LABEL org.opencontainers.image.source=https://github.com/chrisagrams/rhea

ARG TARGETARCH

ENV MINICONDA_HOME=/home/rhea/conda \
    PATH=/home/rhea/conda/bin:$PATH

RUN apt-get update \
  && apt-get install -y --no-install-recommends wget ca-certificates bzip2 gettext-base locales\
  && rm -rf /var/lib/apt/lists/*

# Generate locales
RUN sed -i '/en_US.UTF-8/s/^# *//' /etc/locale.gen \
  && locale-gen \
  && dpkg-reconfigure --frontend=noninteractive locales

RUN useradd -m -s /bin/bash rhea

RUN mkdir -p /home/rhea/app
RUN chown -R rhea:rhea /home/rhea/app

RUN case "$TARGETARCH" in \
    amd64)   CONDA_ARCH=Linux-x86_64   ;; \
    arm64)   CONDA_ARCH=Linux-aarch64   ;; \
    ppc64le) CONDA_ARCH=Linux-ppc64le   ;; \
    s390x)   CONDA_ARCH=Linux-s390x     ;; \
    *)       echo "Unsupported arch: $TARGETARCH" >&2; exit 1 ;; \
  esac \
  && wget -qO /tmp/miniconda.sh "https://repo.anaconda.com/miniconda/Miniconda3-latest-${CONDA_ARCH}.sh" \
  && bash /tmp/miniconda.sh -b -p $MINICONDA_HOME \
  && rm /tmp/miniconda.sh \
  && $MINICONDA_HOME/bin/conda clean -afy 

# Pre‑accept Anaconda channel Terms of Service
RUN mkdir -p $HOME \
  && cat <<EOF > $HOME/.condarc
accepted_terms:
  https://repo.anaconda.com/pkgs/main: yes
plugins:
  auto_accept_tos: true
EOF

WORKDIR /home/rhea/app

RUN conda install -y -c conda-forge uv \
  && conda clean -afy

# Add channels and automatic ToS accept
RUN conda install -y -c conda-forge uv \
  && conda clean -afy \
  && conda config --add channels bioconda \
  && conda config --add channels conda-forge \
  && conda config --set channel_priority strict \
  && conda install -y -n base conda-anaconda-tos \
  && conda config --set plugins.auto_accept_tos yes

RUN uv venv --python 3.10 /home/rhea/venv \
 && . /home/rhea/venv/bin/activate \
 && uv pip install parsl==2025.6.23 proxystore debugpy minio Cheetah3 academy-py

COPY utils/ /home/rhea/app/utils
COPY agent/ /home/rhea/app/agent
COPY manager/ /home/rhea/app/manager

# ENTRYPOINT ["/opt/venv/bin/python"]

