services:
  server:
    image: chrisagrams/rhea-server:latest
    container_name: rhea-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Allow the server to execute Docker agents
    env_file:
        - .env.docker

  redis:
    image: redis:7
    container_name: rhea-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    entrypoint: ["redis-server"]
    command:
      - "--save"
      - ""
      - "--appendonly"
      - "yes"
    restart: unless-stopped
  
  minio:
    image: minio/minio:latest
    container_name: minio
    volumes:
      - ./data/minio:/data
    ports:
      - "9090:9000"
      - "9091:9001"
    environment:
      MINIO_ROOT_USER:     admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"

volumes:
  redis-data:
    name: rhea-redis-data
