FROM debian:stable-slim

ARG TARGETARCH

ENV MINICONDA_HOME=/opt/conda \
    PATH=/opt/conda/bin:$PATH

RUN apt-get update \
  && apt-get install -y --no-install-recommends wget ca-certificates bzip2 \
  && case "$TARGETARCH" in \
    amd64)   CONDA_ARCH=Linux-x86_64   ;; \
    arm64)   CONDA_ARCH=Linux-aarch64   ;; \
    ppc64le) CONDA_ARCH=Linux-ppc64le   ;; \
    s390x)   CONDA_ARCH=Linux-s390x     ;; \
    *)       echo "Unsupported arch: $TARGETARCH" >&2; exit 1 ;; \
  esac \
  && wget -qO /tmp/miniconda.sh "https://repo.anaconda.com/miniconda/Miniconda3-latest-${CONDA_ARCH}.sh" \
  && bash /tmp/miniconda.sh -b -p $MINICONDA_HOME \
  && rm /tmp/miniconda.sh \
  && $MINICONDA_HOME/bin/conda clean -afy \
  && apt-get purge -y wget bzip2 \
  && apt-get autoremove -y \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY utils/ /app/utils
COPY agent/ /app/agent
COPY manager/ /app/manager
COPY lib/academy /app/lib/academy

RUN conda install -y -c conda-forge uv \
  && conda clean -afy

RUN conda config --add channels bioconda \
  && conda config --add channels conda-forge \
  && conda config --set channel_priority strict

RUN uv venv --python 3.10 /opt/venv \
 && . /opt/venv/bin/activate \
 && uv pip install -e /app/lib/academy \
 && uv pip install parsl proxystore

# ENTRYPOINT ["/opt/venv/bin/python"]

