site_name: Rhea
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
  palette:
      # Palette toggle for automatic mode
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/brightness-auto
          name: Switch to light mode

      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default 
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to system preference

markdown_extensions:
  - pymdownx.snippets:
        base_path: '.'
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
  - search
  - autorefs
  - mermaid2
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          paths: ['.']
          options:
            docstring_style: google
            show_source: true
            members_order: source
            inherited_members: true
            merge_init_into_class: true
            show_if_no_docstring: true
            show_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            filters: ["!^_"]
            extensions:
              - griffe_inherited_docstrings
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
            - https://requests.readthedocs.io/en/latest/objects.inv
            - https://modelcontextprotocol.github.io/python-sdk/objects.inv

nav:
  - Home: index.md
  - Overview: overview.md
  - Examples: examples.md
  - Client Library: client.md
  - Server Deployment: deploy.md