name: Build and Publish (PyPI)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Sync dependencies
        run: uv sync --frozen

      - name: Build
        run: uv build

      - name: Publish to PyPI
        run: uv publish